global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs'
    static_configs:
      - targets: ['host.docker.internal:3000']  # тут порт твоего node.js приложения

  # Добавить MySQL и другие, если нужно
